export const sheetContent = {
  range: "'Armenian brands'!A1:Z1000",
  majorDimension: "ROWS",
  values: [
    [
      "name",
      "where to find",
      "labels",
      "labels arm, translated",
      "labels ru, translated",
    ],
    [
      "ZGST",
      "https://zgst.am/",
      "Tactical Equipment, Tactical clothing",
      "Մարտավարական տեխնիկա, Մարտավարական հագուստ",
      "Тактическое снаряжение, Тактическая одежда",
    ],
    [
      "Dufflebag",
      "https://dufflebag.am/",
      "shoe, shirt, store, Tactical Equipment, online store",
      "կոշիկ, վերնաշապիկ, խանութ, մարտավարական տեխնիկա, առցանց խանութ",
      "обувь, рубашка, магазин, Тактическое снаряжение, интернет-магазин",
    ],
    [
      "Lernetsee",
      "https://it-it.facebook.com/lernetsee/",
      "shoe, boot, hicking",
      "կոշիկ, կոշիկ, կոշիկ",
      "ботинок, ботинок, походка",
    ],
    [
      "Danz",
      "https://danz.am/",
      "Glasses, optical glasses, sunglasses",
      "Ակնոցներ, օպտիկական ակնոցներ, արևային ակնոցներ",
      "Очки, оптические очки, солнцезащитные очки",
    ],
    [
      "Baags",
      "https://www.baaags.store/",
      "Bag, banana bag, backpack",
      "Պայուսակ, բանանի պայուսակ, ուսապարկ",
      "Сумка, сумка-банан, рюкзак.",
    ],
    [
      "Berq",
      "https://www.facebook.com/profile.php?id=100063550092161",
      "Designer clothing, clothing, banana bag",
      "Դիզայներական հագուստ, հագուստ, բանանի պայուսակ",
      "Дизайнерская одежда, одежда, сумка-банан",
    ],
    [
      "Bezoo",
      "https://www.facebook.com/bezoobicycle",
      "Bicicles",
      "Հեծանիվներ",
      "Велосипеды",
    ],
    [
      "Gisaneh Jewelry",
      "https://www.facebook.com/GisanehJewelry/",
      "Silver, jewelry, woman",
      "Արծաթ, զարդեր, կին",
      "Серебро, украшения, женщина",
    ],
    [
      "distinto",
      "https://www.facebook.com/distintocraft/",
      "eco, bag, recicled, woman",
      "էկո, պայուսակ, վերամշակված, կին",
      "эко, сумка, вторсырье, женщина",
    ],
    [
      "shooghik",
      "https://www.facebook.com/shooghik",
      "knitted, bag, hat, amrakits",
      "տրիկոտաժե, պայուսակ, գլխարկ, amrakits",
      "вязаная, сумка, шапка, амракитс",
    ],
    [
      "LOOM Weaving",
      "http://www.loom-weaving.com/",
      "knitwear, clothing",
      "տրիկոտաժեղեն, հագուստ",
      "трикотаж, одежда",
    ],
    ["AWI", "https://awi.am/", "watches", "ժամացույցներ", "часы"],
    [
      "Zakaryan",
      "https://zakaryan.am/",
      "jeans, pants, clothing",
      "ջինսեր, շալվարներ, հագուստ",
      "джинсы, брюки, одежда",
    ],
    [
      "#SPORT",
      "https://www.facebook.com/hashtagsportarmenia",
      "Hoodie, T-shirt",
      "Հուդի, շապիկ",
      "Толстовка, футболка",
    ],
    [
      "Tosp",
      "https://www.facebook.com/tosp.armenia",
      "clothing, print",
      "հագուստ, տպագիր",
      "одежда, принт",
    ],
    [
      "Prime",
      "https://www.facebook.com/primecasualwear",
      "clothing, print, hoodie, t-shirt",
      "հագուստ, պրինտ, hoodie, շապիկ",
      "одежда, принт, толстовка, футболка",
    ],
    [
      "Made in Kurtan",
      "https://www.facebook.com/madeinkurtan",
      "jackets, backpack",
      "բաճկոններ, ուսապարկ",
      "куртки, рюкзак",
    ],
    [
      "elbat",
      "https://elbat.am/",
      "car accumulator, battery",
      "մեքենայի կուտակիչ, մարտկոց",
      "автомобильный аккумулятор, аккумулятор",
    ],
    [
      "NURWIND Duduk Company",
      "https://www.nurwind.com/en/",
      "Duduk, musical instrument",
      "Դուդուկ, երաժշտական \u200b\u200bգործիք",
      "Дудук, музыкальный инструмент",
    ],
    [
      "Arcolad armenian chocolat",
      "https://shop.arcolad.am/en",
      "chockolat, sweets",
      "շոկոլադ, քաղցրավենիք",
      "шоколад, сладости",
    ],
    [
      "Busy Baby",
      "https://www.facebook.com/profile.php?id=100040741248333",
      "baby, games, toy, kid",
      "երեխա, խաղեր, խաղալիք, երեխա",
      "малыш, игры, игрушка, малыш",
    ],
    [
      "Light Affect",
      "https://lightaffect.am/",
      "T-shirt, clothing, hoodie, jacket, trousers, hats",
      "Շապիկ, հագուստ, գլխարկ, բաճկոն, տաբատ, գլխարկներ",
      "Футболка, одежда, толстовка, куртка, брюки, шапки",
    ],
    [
      "Lalunz",
      "https://www.lalunz.com/",
      "clothing, child, baby",
      "հագուստ, երեխա, երեխա",
      "одежда, ребенок, малышка",
    ],
    [
      "Arnakhsh",
      "https://www.facebook.com/Arnakhsh",
      "Silver, jewelry, woman",
      "Արծաթ, զարդեր, կին",
      "Серебро, украшения, женщина",
    ],
    [
      "Narekatsin",
      "https://www.facebook.com/narekatsin",
      "Silver, jewelry, woman, historical",
      "Արծաթ, զարդեր, կին, պատմ",
      "Серебро, ювелирные изделия, женские, исторические",
    ],
    [
      "ARLI",
      "https://www.facebook.com/arlishoes",
      "shoe, women",
      "կոշիկ, կանայք",
      "обувь, женщины",
    ],
    [
      "Behez",
      "https://www.facebook.com/profile.php?id=100063713353998",
      "clothing, girl, women",
      "հագուստ, աղջիկ, կին",
      "одежда, девушка, женщины",
    ],
    [
      "sose",
      "https://www.facebook.com/sose.jewellery",
      "jewelry, womern",
      "զարդեր, կանացի",
      "украшения, женские",
    ],
    [
      "Dayan",
      "https://www.facebook.com/dayanhandmade/",
      "Clothing, bags, women",
      "Հագուստ, պայուսակներ, կանացի",
      "Одежда, сумки, женщины",
    ],
    [
      "Erebuni clothing",
      "https://erebuniclothing.com/",
      "men, ties",
      "տղամարդիկ, փողկապներ",
      "мужчины, галстуки",
    ],
    [
      "Dippy",
      "https://www.wildberries.ru/seller/813831#c90022525",
      "pajamas, clothing",
      "պիժամա, հագուստ",
      "пижамы, одежда",
    ],
    [
      "Hayka handmade",
      "https://www.facebook.com/haykahandmade",
      "knitted, jewelry",
      "տրիկոտաժե, զարդեր",
      "вязаные, украшения",
    ],
    [
      "Votnaman",
      "https://www.facebook.com/votnaman",
      "shoes",
      "կոշիկներ",
      "обувь",
    ],
    [
      "Cheers",
      "https://www.facebook.com/cheersArmenia",
      "dried fruit, sweet",
      "չիր, քաղցր",
      "сухофрукты, сладкие",
    ],
    [
      "lentex",
      "https://www.facebook.com/lentexllc/",
      "clothing, sock, hoodie, t-shirt, gyumri",
      "հագուստ, գուլպա, գլխարկ, շապիկ, Գյումրի",
      "одежда, носок, толстовка, футболка, Гюмри",
    ],
    [
      "Artsocks",
      "https://www.artsocks.am/collections/armenian-art",
      "sock, art, clothing",
      "գուլպաներ, արվեստ, հագուստ",
      "носок, искусство, одежда",
    ],
    [
      "Wilarso fabrics",
      "https://www.facebook.com/profile.php",
      "handmade, clothing, knitware",
      "ձեռագործ, հագուստ, տրիկոտաժե",
      "ручная работа, одежда, трикотаж",
    ],
    ["Texart", "https://texart.am/", "prints", "տպագրություններ", "принты"],
    [
      "Soft Papyrus",
      "http://www.softpapyrus.am/",
      "paper towel, toilet paper, paper tissue, napkins",
      "թղթե սրբիչ, զուգարանի թուղթ, թղթե անձեռոցիկ, անձեռոցիկներ",
      "бумажное полотенце, туалетная бумага, бумажные салфетки, салфетки",
    ],
    [
      "Silksoft",
      "https://www.facebook.com/SilksSoft/",
      "paper towel, toilet paper, paper tissue, napkins",
      "թղթե սրբիչ, զուգարանի թուղթ, թղթե անձեռոցիկ, անձեռոցիկներ",
      "бумажное полотенце, туалетная бумага, бумажные салфетки, салфетки",
    ],
    [
      "Shogha",
      "https://www.facebook.com/shogha",
      "shampoo, hair balsam, skin care",
      "շամպուն, մազերի բալզամ, մաշկի խնամք",
      "шампунь, бальзам для волос, уход за кожей",
    ],
    [
      "Sweetdiet Armenia",
      "https://www.facebook.com/sweetdietarm",
      "dried fruit, food, snack, bars, sweet",
      "չիր, սնունդ, խորտիկ, բարեր, քաղցրավենիք",
      "сухофрукты, еда, закуски, батончики, сладкие",
    ],
    [
      "Cotton Flakes",
      "https://www.facebook.com/PEKamoBarseghyan",
      "gyumri, bed sheets",
      "Գյումրի, անկողնային ծածկոցներ",
      "Гюмри, простыни",
    ],
    [
      "Duson",
      "https://duson.am/",
      "matrass, orthopedical",
      "մատրասա, օրթոպեդիկ",
      "матрас ортопедический",
    ],
    [
      "ReArmenia",
      "https://rearmenia.com/",
      "civil, donation",
      "քաղաքացիական, նվիրատվություն",
      "гражданский, пожертвование",
    ],
    [
      "ARMENIAN PEACE",
      "http://ap.am/",
      "peace, donation",
      "խաղաղություն, նվիրատվություն",
      "мир, пожертвование",
    ],
    [
      "Tumanyan notebooks",
      "https://tumanyannotebooks.com/",
      "notebook, copybook, journal, sketchbook",
      "տետր, տետր, մատյան, էսքիզ",
      "блокнот, тетрадь, дневник, альбом для рисования",
    ],
    [
      "Dobby am",
      "https://www.facebook.com/dobby.am/",
      "sock, art, clothing",
      "գուլպաներ, արվեստ, հագուստ",
      "носок, искусство, одежда",
    ],
    [
      "Bzbzik toys",
      "https://www.facebook.com/Bzbzik/",
      "toys, wood, swedish wall, intelectual, marbles",
      "խաղալիքներ, փայտ, շվեդական պատ, ինտելեկտուալ, մարմար",
      "игрушки, дерево, шведская стенка, интеллектуал, мрамор",
    ],
    [
      "becorestonecarving",
      "https://www.instagram.com/becorestonecarving/?igshid=N2ZiY2E3YmU%3D",
      "Khachkar, stone, arevkhach, sun clock, carving",
      "Խաչքար, քար, արևխաչ, արևային ժամացույց, փորագրություն",
      "Хачкар, камень, аревхач, солнечные часы, резьба",
    ],
    [
      "onyvabags",
      "https://www.instagram.com/onyvabags/?igshid=N2ZiY2E3YmU%3D",
      "bags, knitted",
      "պայուսակներ, տրիկոտաժե",
      "сумки вязаные",
    ],
    [
      "dens_hovhannisyan",
      "https://instagram.com/dens_hovhannisyan?igshid=N2ZiY2E3YmU=",
      "designer clothing, clothing, woman",
      "դիզայներական հագուստ, հագուստ, կին",
      "дизайнерская одежда, одежда, женщина",
    ],
    [
      "Sha",
      "https://instagram.com/sha_____official?igshid=N2ZiY2E3YmU=",
      "designer clothing, clothing, woman",
      "դիզայներական հագուստ, հագուստ, կին",
      "дизайнерская одежда, одежда, женщина",
    ],
    [
      "thebagarmenia",
      "https://www.instagram.com/thebagarmenia/?igshid=N2ZiY2E3YmU%3D",
      "bags, lather, arevkhach",
      "պայուսակներ, փրփուր, արևխաչ",
      "мешки, мыльная пена, аревхач",
    ],
    [
      "Arnoush",
      "http://arnoush.am/en/",
      "almond butter, peanut butter, tahini ",
      "նուշի կարագ, գետնանուշի կարագ, թահին ",
      "миндальное масло, арахисовое масло, тахини ",
    ],
    [
      "Suitable",
      "https://www.facebook.com/SuitableArmenia",
      "stand desk, desk",
      "նստարան, գրասեղան",
      "стойка, письменный стол",
    ],
    [
      "coxy",
      "https://www.instagram.com/coxy_official/",
      "underwear, lingerie ",
      "ներքնազգեստ, ներքնազգեստ ",
      "нижнее белье, нижнее белье ",
    ],
    [
      "tarenihandmade",
      "https://www.instagram.com/tarenihandmade/",
      "baby, games, toy, kid, woven",
      "երեխա, խաղեր, խաղալիք, երեխա, հյուսված",
      "малыш, игры, игрушка, малыш, плетеный",
    ],
    [
      "Other Mood",
      "https://othermood.com/hy",
      "designer clothing, male",
      "դիզայներական հագուստ, արական",
      "дизайнерская одежда, мужская",
    ],
    [
      "Man In Town",
      "https://www.facebook.com/ManInTownEVN/",
      "designer clothing, woman",
      "դիզայներական հագուստ, կին",
      "дизайнерская одежда, женщина",
    ],
    [
      "theday",
      "https://theday.am/",
      "durable, functional, bag, hiking",
      "դիմացկուն, ֆունկցիոնալ, պայուսակ, արշավ",
      "прочная, функциональная, сумка, походная",
    ],
  ],
};
